# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prep' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prep
pod "CTPanoramaView", "~> 1.0"
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'ScalingCarousel'
pod 'DTZFloatingActionButton'
pod 'expanding-collection', '~> 1.0.3' swift 3
pod 'GoogleSignIn'

target 'PrepTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrepUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
